### ISSUE TITLE
Useless use

### ISSUE THREAD

**Issue by AlexDaniel** [jnthn/oo-monitors#11]
When installing this module:
```
===> Testing: OO::Monitors:ver<1.1>
WARNINGS for /home/travis/.zef/store/oo-monitors.git/b9de07c277f0a9fa805bb18113788228f6acfd3b/t/condition.t:
Useless use of constant value not-empty in sink context (lines 15, 20)
Useless use of constant value not-full in sink context (lines 12, 22)
```

**Comment by jnthn** [comment]
That'd be a Rakudo bug. The [values in question](https://github.com/jnthn/oo-monitors/blob/master/t/condition.t#L15) are arguments to a macro, and the argument is [used](https://github.com/jnthn/oo-monitors/blob/master/lib/OO/Monitors.pm6#L107).

**Comment by zoffixznet** [comment]
This issue can probably closed, I golfed it down to something that doesn't involve this module at all:

```perl6
use experimental :macros; macro z($) { quasi {} }; z $;
```

**Comment by jnthn** [comment]
Verified that, with the Rakudo warning bug fixed, the warning in this module is also gone.
