### ISSUE TITLE
Tests apparently fail with the latest Rakudo build

### ISSUE THREAD

**Issue by JJ** [jnthn/oo-monitors#14]
It might be something upstream, but this is where the build shows the error: https://travis-ci.org/perl6/doc/jobs/474784626

**Comment by jnthn** [comment]
Yes, that'll be a Rakudo regression.

**Comment by jonathanstowe** [comment]
Scary canary :-)

**Comment by jnthn** [comment]
Fixed in Rakudo HEAD.
